# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='ecprotobuf',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rmessage.proto\x12\necprotobuf\"\xa3\x01\n\x0b\x45\x63ReqHeader\x12\x0b\n\x03\x63md\x18\x01 \x01(\r\x12\x0b\n\x03seq\x18\x02 \x01(\x04\x12\x0e\n\x06userid\x18\x03 \x01(\r\x12\x10\n\x08platform\x18\x04 \x01(\r\x12\x0f\n\x07version\x18\x05 \x01(\r\x12\x0b\n\x03key\x18\x06 \x01(\t\x12\x0b\n\x03len\x18\x07 \x01(\x03\x12\x10\n\x08\x63ompress\x18\x08 \x01(\x08\x12\x0b\n\x03\x62uf\x18\t \x01(\x0c\x12\x0e\n\x06\x63orpid\x18\n \x01(\x03\"\xc5\x01\n\x0b\x45\x63ResHeader\x12\x0b\n\x03\x63md\x18\x01 \x01(\r\x12\x0b\n\x03seq\x18\x02 \x01(\x04\x12\x0e\n\x06userid\x18\x03 \x01(\r\x12\x10\n\x08platform\x18\x04 \x01(\r\x12\x0f\n\x07version\x18\x05 \x01(\r\x12\x0b\n\x03key\x18\x06 \x01(\t\x12\x0b\n\x03len\x18\x07 \x01(\x03\x12\x10\n\x08\x63ompress\x18\x08 \x01(\x08\x12\x0e\n\x06origin\x18\t \x01(\t\x12\x0f\n\x07\x65rrcode\x18\n \x01(\r\x12\x0f\n\x07\x65rrinfo\x18\x0b \x01(\t\x12\x0b\n\x03\x62uf\x18\x0c \x01(\x0c\x32N\n\x08Grpcfunc\x12\x42\n\x0cGrpcDataFunc\x12\x17.ecprotobuf.EcReqHeader\x1a\x17.ecprotobuf.EcResHeader\"\x00\x62\x06proto3')
)




_ECREQHEADER = _descriptor.Descriptor(
  name='EcReqHeader',
  full_name='ecprotobuf.EcReqHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmd', full_name='ecprotobuf.EcReqHeader.cmd', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seq', full_name='ecprotobuf.EcReqHeader.seq', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='userid', full_name='ecprotobuf.EcReqHeader.userid', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='platform', full_name='ecprotobuf.EcReqHeader.platform', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='ecprotobuf.EcReqHeader.version', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key', full_name='ecprotobuf.EcReqHeader.key', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='len', full_name='ecprotobuf.EcReqHeader.len', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='compress', full_name='ecprotobuf.EcReqHeader.compress', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='buf', full_name='ecprotobuf.EcReqHeader.buf', index=8,
      number=9, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='corpid', full_name='ecprotobuf.EcReqHeader.corpid', index=9,
      number=10, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=193,
)


_ECRESHEADER = _descriptor.Descriptor(
  name='EcResHeader',
  full_name='ecprotobuf.EcResHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmd', full_name='ecprotobuf.EcResHeader.cmd', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seq', full_name='ecprotobuf.EcResHeader.seq', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='userid', full_name='ecprotobuf.EcResHeader.userid', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='platform', full_name='ecprotobuf.EcResHeader.platform', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='ecprotobuf.EcResHeader.version', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key', full_name='ecprotobuf.EcResHeader.key', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='len', full_name='ecprotobuf.EcResHeader.len', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='compress', full_name='ecprotobuf.EcResHeader.compress', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='origin', full_name='ecprotobuf.EcResHeader.origin', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='errcode', full_name='ecprotobuf.EcResHeader.errcode', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='errinfo', full_name='ecprotobuf.EcResHeader.errinfo', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='buf', full_name='ecprotobuf.EcResHeader.buf', index=11,
      number=12, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=393,
)

DESCRIPTOR.message_types_by_name['EcReqHeader'] = _ECREQHEADER
DESCRIPTOR.message_types_by_name['EcResHeader'] = _ECRESHEADER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EcReqHeader = _reflection.GeneratedProtocolMessageType('EcReqHeader', (_message.Message,), dict(
  DESCRIPTOR = _ECREQHEADER,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:ecprotobuf.EcReqHeader)
  ))
_sym_db.RegisterMessage(EcReqHeader)

EcResHeader = _reflection.GeneratedProtocolMessageType('EcResHeader', (_message.Message,), dict(
  DESCRIPTOR = _ECRESHEADER,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:ecprotobuf.EcResHeader)
  ))
_sym_db.RegisterMessage(EcResHeader)



_GRPCFUNC = _descriptor.ServiceDescriptor(
  name='Grpcfunc',
  full_name='ecprotobuf.Grpcfunc',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=395,
  serialized_end=473,
  methods=[
  _descriptor.MethodDescriptor(
    name='GrpcDataFunc',
    full_name='ecprotobuf.Grpcfunc.GrpcDataFunc',
    index=0,
    containing_service=None,
    input_type=_ECREQHEADER,
    output_type=_ECRESHEADER,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GRPCFUNC)

DESCRIPTOR.services_by_name['Grpcfunc'] = _GRPCFUNC

# @@protoc_insertion_point(module_scope)
